### ISSUE TITLE
Email for related papers authors: Exclude submitting author

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#991] opened 2021-06-19 18:26 UTC
e.g. https://biofactoid.org/document/8ba80a9a-95a8-47ca-ad56-e9cc77d986f0

**Comment by jvwong** [comment] 2021-07-14 14:56
Another example: https://biofactoid.org/document/87c31b61-e29d-4cef-bdd5-9dd8167fb218

This will probably get worse, as more docs are added, which I suppose is a good problem to have.

**Comment by jvwong** [comment] 2021-07-14 15:09
Also, I wonder what happened in the above case: It looks like the author tried to add the title for the related-author email they got (from their own, organic submission) 

![Admin-Biofactoid](https://user-images.githubusercontent.com/4706307/125645850-68b421cd-ccfd-4ec6-a6cd-6e2a3c8667f6.png)

Looks like maybe  it either failed to pick up the paper? They managed to re-enter it successfully through the homepage:

https://biofactoid.org/document/8d0c4819-2815-4185-88d7-f4e7a4483b1d

So in this case, the contributing author who got a viral email ended up adding the paper, so it worked in a roundabout way.

**Comment by jvwong** [comment] 2021-07-14 15:13
Maybe the idea here is to send the submitting author a bunch of articles of theirs they may want to consider adding as well?

**Comment by maxkfranz** [comment] 2021-07-14 15:53
Does it matter if the emails go to an existing user or a new user as long as the emails result in new factoids?

Instead of blocking emails for existing users altogether could we:

- Consider tweaking the email text a bit for existing users so that the email feels more fitting (e.g. acknowledge that the user contributed before and we have another opportunity for them to contribute).
- Consider the timing and frequency of these emails.
  - Repeated engagement versus one-time engagement.
  - Receiving a lot of emails at once versus drip-feeding emails.

**Comment by jvwong** [comment] 2021-07-16 13:49
At this point in the game, need to capitalize on willingness and attention of user who has just tried it successfully. 

Another user of note added their paper from the invite recently -  then added 4 more right after So they "get it", they are "trained" and they have all these other papers/pathways in their head that we should capitalize on.

Tough part is if they use a random email, how do we know who's who

**Comment by maxkfranz** [comment] 2021-08-03 20:14
Since we all agree getting more articles in the system is a high priority and this seems to help with that, is there anything else that we need to consider here?  It seems to be working more or less as intended as-is.

**Comment by jvwong** [comment] 2021-08-04 14:52
There's no low hanging fruit. I don't think sending the contributing author(s) one or two emails is a huge problem.

**Comment by maxkfranz** [comment] 2021-08-04 16:48
OK, if there's nothing else then let's close this for now

**Closed by maxkfranz** 2021-08-04 16:48 UTC
