### ISSUE TITLE
Update Document API for data formats: TXT, SBGN, BioPAX

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#685] opened 2020-03-17 21:28 UTC
The various web service API endpoints for data formats are either broken (BIOPAX, SBGN) or out of sync with model updates (TXT). The goal is to update and test so they are functioning and providing correct data in return.

**Comment by jvwong** [comment] 2020-03-20 16:40
@metincansiper - 1. were you the author? 2. do you have the ability to update service at [https://biopax.baderlab.org/convert/](https://biopax.baderlab.org/convert/)

**Comment by metincansiper** [comment] 2020-03-31 01:24
Interestingly ``EntityReference`` objects cannot be added to biopax model (I mean even not created) as I described here (https://github.com/BioPAX/Paxtools/issues/47).

**Comment by maxkfranz** [comment] 2020-03-31 16:51
If this is a problem only for incomplete entities (e.g. ungrounded nodes), then one alternative would be to exclude those nodes in the biopax export.  There should generally not be any ungrounded nodes in current interface, so it's a fair assumption.

**Comment by maxkfranz** [comment] 2020-03-31 16:53
Note that a complex does not have a grounding, so something like `ent.complete() === false` would probably be the best way to identify problematic nodes.

**Comment by metincansiper** [comment] 2020-03-31 19:33
@maxkfranz looks like the problem is not related to whether the entity is complete (I need to check if that is another problem as well but this one is different). Following up the response of Igor in the issue that I opened in paxtools, I see that ``EntityReference`` is an abstract class. I was not aware of that and so was trying to assign the entity to that if its type is neither protein nor chemical. Now I will probably handle that case as an exception. 

However, the real thing to consider is why we had some entities that is neither of protein nor chemical. I realized that there are new types like ggp, dna and rna. As far as I can understand from some client side code we must interpret them as proteins. Is that correct? By assuming so I will input them as proteins to the converter which will probably solve this problem. 

The other problem is about the complexes. Do we want them to be included in the converter? If we do not want it I can just ignore the interactions that has complex in one or both side. Otherwise, I can make the needed implementation to consider complexes in both the converter and the factoid web app sides.

**Comment by metincansiper** [comment] 2020-03-31 19:48
>Note that a complex does not have a grounding, so something like ent.complete() === false would probably be the best way to identify problematic nodes.

I just realized this comment. So, I assume that we must consider the complexes in the converter.

**Comment by jvwong** [comment] 2020-03-31 20:08
> However, the real thing to consider is why we had some entities that is neither of protein nor chemical. I realized that there are new types like ggp, dna and rna. As far as I can understand from some client side code we must interpret them as proteins. Is that correct? By assuming so I will input them as proteins to the converter which will probably solve this problem.

Yeah you're seeing some of the trade-off of being as flexible as possible for users: They can attach an NCBI Gene ID to a genomic/DNA region (e.g. binding to a promoter region) an RNA Region (e.g. transcribed DNA region) or Protein (i.e. translated RNA region). 
If they leave it at the default 'ggp' then it refers to one of these three physical entities and not a 'gene' per se. I guess protein is a good guess, since all a data consumer will really care about is the NCBI Gene ID, but some transcribed regions don't have a corresponding proteins so that wouldn't make sense.

**Comment by metincansiper** [comment] 2020-03-31 22:31
>Yeah you're seeing some of the trade-off of being as flexible as possible for users: They can attach an NCBI Gene ID to a genomic/DNA region (e.g. binding to a promoter region) an RNA (e.g. transcribed) or Protein (i.e. translated ).

@jvwong thank you for the explanation. When I read my comment again I see that I had a typo that changes the meaning of my whole comment. I actually did not intended to put "why" in this sentence: "However, the real thing to consider is why we had some entities that is neither of protein nor chemical." I was meaning that "However, the real thing to consider is that we had some entities that is neither of protein nor chemical". I actually was not intended to question why it is, I but that typo changed the meaning of the whole sentence.

>If they leave it at the default 'ggp' then it refers to one of these three physical entities and not a 'gene' per se. I guess protein is a good guess, since all a data consumer will really care about is the NCBI Gene ID, but some transcribed regions don't have a corresponding proteins so that wouldn't make sense.

- I looked more into the biopax level 3 documentation. I see that there are physical entity classes called "RNA" and "DNA". Therefore, I guess we must use these ones for entites with type of "dna" and "rna" to be more specific. Is that correct?
- Should I just check the data source for the "ggp" entities to figure out whether they must be assigned to a chemical or protein? If they are incomplete I can treat them as the other incomplete entities.
- About the incomplete entities: Initially I was thinking of classifying any type that is not a match for the converter as the general PhysicalEntity. Looks like incomplete entities fits to that case. However, I was also supposing that I could assign a generic EntityReference for that PhysicalEntity instances. Looks like that PhysicalEntity class is not abstract but EntityReference class is abstract. If I can figure out how to create an entity reference for such generic PhysicalEntity's I can cover the incomplete entities in that way. But, if there is no way I can probably skip them as Max mentioned.

**Comment by jvwong** [comment] 2020-04-01 15:24
> I looked more into the biopax level 3 documentation. I see that there are physical entity classes called "RNA" and "DNA". Therefore, I guess we must use these ones for entites with type of "dna" and "rna" to be more specific. Is that correct?

I'm not BioPAX expert but...  
  - 'DNA' should be mapped to bp:DNARegion
  - 'RNA' should be mapped to either bp:RNARegion or bp:RNA (I've seen both in PC)

> Should I just check the data source for the "ggp" entities to figure out whether they must be assigned to a chemical or protein? If they are incomplete I can treat them as the other incomplete entities.

What you said above is the best approximation.

**Comment by maxkfranz** [comment] 2020-04-01 16:07
For `ggp`, I expect that a common, concrete superclass of `DNARegion` and `RNARegion` -- if it exists -- would be appropriate.  Emek would probably be the best person to weigh in on this issue.

**Comment by metincansiper** [comment] 2020-04-01 19:02
>For ggp, I expect that a common, concrete superclass of DNARegion and RNARegion -- if it exists -- would be appropriate. Emek would probably be the best person to weigh in on this issue.

From the level 3 documentation (http://www.biopax.org/release/biopax-level3-documentation.pdf) both ``DNARegion`` and ``RNARegion`` are direct subclasses of ``PhysicalEntity``. I mean ``PhysicalEntity`` is directly parent class of both of them.

**Comment by maxkfranz** [comment] 2020-04-01 19:06
PhysicalEntity doesn't describe ggp very well, but maybe it's the best we can do

**Comment by metincansiper** [comment] 2020-04-01 19:38
>PhysicalEntity doesn't describe ggp very well, but maybe it's the best we can do

@maxkfranz  Do you mean the PhysicalEntity base class? How about assigning to a protein or chemical based on the datasource as I mentioned instead?

**Comment by metincansiper** [comment] 2020-04-01 19:56
One point with using the PhysicalEntity base class is that if we use it for ggp entities then we probably cannot assign any entity reference for them. As I mentioned the base EntityReference class is abstract.

**Comment by gbader** [comment] 2020-04-01 20:56
ggp should probably be Gene in BioPAX
dna molecule should probably be Dna in BioPAX
rna molecule should probably be Rna in BioPAX

What are the various cases that are being looked at here?

**Comment by metincansiper** [comment] 2020-04-02 16:58
>ggp should probably be Gene in BioPAX
dna molecule should probably be Dna in BioPAX
rna molecule should probably be Rna in BioPAX

Thank you @gbader!

Looks like``Gene`` is not a subclass of ``PhysicalEntity`` but it is a subclass of ``Entity`` which is also the parent class of ``PhysicalEntity``. And ``Entity`` looks like a very general class in biopax as the other subclasses of it are ``Interaction`` and ``Pathway``.

- Actually I was imagining that the entities of factoid would match the PhysicalEntity types in biopax. Then, I guess that my that assumption must be wrong.
- If we map ggp to ``Gene`` then ggp entities would not have some properties that other entities has. I do not know the whole list for now but what I can see so far are entity reference and cellular location. Is it normal or expected for ggp entities?

**Comment by metincansiper** [comment] 2020-04-02 18:45
I just realized that in factoid ``ggp`` is described as "gene or gene product". I made a search in biopax and see that RelationshipXref's can have relationshipType properties which is defined as the following:

```
relationshipType - (0 or more object:RelationshipTypeVocabulary)
This property names the type of relationship between the BioPAX
object linked from, and the external object linked to, such as 'gene of
this protein', or 'protein with similar sequence'. This should reference
to the PSI Molecular Interaction ontology (MI) Cross Reference type.
Homepage at http://www.psidev.info/. Browse at
http://www.ebi.ac.uk/ontology-lookup/browse.do?
ontName=MI&termId=MI%3A0353&termName=cross-reference
%20type. See the section on controlled vocabularies in Section 4 for
89
more information. 
```

Therefore, I wonder if we can just map ggp to a protein and add attach a RelationshipTypeVocabulary that tells 'gene of
this protein'?

How does that sound?

**Comment by jvwong** [comment] 2020-04-02 19:31
Just trying to summarize: 
 
| Factoid Model   | BioPAX Class      | Comments  |
|:---------------:|:----------------:|:-----------|
| ggp                   | ?                         |   Must be `bp:PhysicalEntity` in order to be participant in interactions (exclusing `bp:GeneticInteraction`) |
| DNA                  | DNARegion        |   |
| RNA                  | RNA                    |   |
| Protein              | Protein               |   |

Proposal: We'd like to map `ggp` to something generic in BioPAX, the closest parent  being `bp:PhysicalEntity`.
Issue:  How to attach the Factoid grounding info (NCBI Gene ID) to `bp:PhysicalEntity` - EntityReference necessarily refers to a physical entity (DNA, RNA, Protein), forcing us to  choose/guess.

**Comment by jvwong** [comment] 2020-04-02 19:54
@metincansiper is it possible to simply assign an `bp:xref` to a `bp:PhysicalEntity`?

**Comment by metincansiper** [comment] 2020-04-02 23:54
Here is the list of properties for a PhysicalEntity: 
```
cellularLocation, feature, memberPhysicalEntity,
notFeature, availability, comment, dataSource, evidence, name, xref
```
Yes a PhysicalEnitity may have xref so I guess we can attach the grounding information but it cannot have an EntityReference. For the other entities we were storing the xref in the EntityReference rather than the Entity itself (I do not know if there is also a need to store it in the Enity itself as well). If we are okay not to have an EntityReference for ggp entities represented by PhysicalEntity, yes we can store their grounding information in the PhysicalEntity itself.

However, the other related issue is about how to handle the interactions where one or both side is one of the new entities. As you may remember we have a document called "Factoid binary interaction types" and how the different cases handled for biopax export was discussed there. However, in that document something were dependent on the enitity types. For example, if the interaction type coming from factoid is ``OtherInteraction`` which is signed then whether the target is protein or chemical affects the resulting biopax interactions a lot. 

I think we must have an updated document considering the new entity types in factoid. I will try to come up with a proposal but to be able to decide on the cases where ggp is included we must decide whether to use PhysicalEntity for sure to cover ggp. I mean are we using that considering my related response?

The other issue is about the complexes. How do we want to consider them? Do we want to create a ComplexAssembly Interaction for them, I mean Interaction for the complexes themselves? And/or do we want to include the factoid interactions where one end is a complex in the exported biopax (maybe we can just create top level interactions for them)?

**Comment by jvwong** [comment] 2020-04-03 01:06
Good points. Let's move all of this to the Google Doc and update.

**Comment by gbader** [comment] 2020-04-03 03:29
> Must be `bp:PhysicalEntity` in order to be participant in interactions (excluding `bp:GeneticInteraction`)

We could use the more generic Interaction class to capture interactions involving a ggp that would be mapped to a gene. Interaction is not restricted to physical entities.

**Comment by gbader** [comment] 2020-04-03 03:30
> The other issue is about the complexes. How do we want to consider them? Do we want to create a ComplexAssembly Interaction for them, I mean Interaction for the complexes themselves? And/or do we want to include the factoid interactions where one end is a complex in the exported biopax (maybe we can just create top level interactions for them)?

We don't need to create a ComplexAssembly interaction, as the user is not discussing the assembly process. We can treat the complex as an atomic unit and just describe it with the Complex class, which can participate in most interactions.

**Comment by metincansiper** [comment] 2020-04-07 03:24
I created a document that I mentioned (https://docs.google.com/document/d/1CfnJNpbRFmuc7LrtcD7VcQi-sSHM7XrTtKIR5Uo_ShI/edit?usp=sharing). 

In the document the parts that are deleted (I mean they will no longer be in the original document) are highlighted by red and the parts that are included are highlighted by orange. I also added some comments to specify why I thought in that way and to ask some questions (there are parts I am not sure about). 

Based on your feedback and/or answers to questions we can decide the final version of the document. After that i will paste it to the related part of "Factoid binary interaction types" document.

You must be able to comment with that link. If commenting would not be enough I can share a link to edit with you through the email.

**Comment by metincansiper** [comment] 2020-04-17 18:45
@jvwong I created the PR #709 for this issue. It covers the updates for biopax and sbgn. However. you also mentioned that TXT export  is out of sync as well for the model updates.

What updates may be needed considering TXT export. Currently a sample of what that service returns is:

```
TP53 activates (?) .
egfr interacts with EGF via phosphorylation.
EGF activates MDM2 via dephosphorylation.
zinc inhibits PODXL2 .
iodine interacts with (?) .
PRH1 interacts with TP53 via methylation.
```

It goes through the interactions as biopax export does.

**Comment by maxkfranz** [comment] 2020-04-20 19:51
I think that the text export is just the same as `toString()` for each interaction.  That means it should just be the same as whatever you see in the UI for the edge popover.  So unless something has broken w.r.t. text export, it's probably fine as-is.

**Comment by metincansiper** [comment] 2020-04-20 19:57
I guess one thing to consider would be about if we want anything special for the complexes.

**Closed** 2020-04-22 14:39 UTC
Labels: bug
