### ISSUE TITLE
Catch error from request to REACH and display a message

### ISSUE THREAD

**Issue by sacdallago** [PathwayCommons/factoid#172] opened 2018-02-01 14:44 UTC
As from https://github.com/PathwayCommons/factoid/issues/171#issuecomment-362285560 , REACH seems to throw back some kind of error which is not caught (nor displayed) properly.

**Comment by sacdallago** [comment] 2018-03-06 20:11
- Relevant in _seed_ page as described in #20
- Logging error from REACH

**Comment by d2fong** [comment] 2018-03-07 16:00
@sacdallago I can't seem to reproduce the error you got in #171  on both my local development version of Factoid and the version at factoid.baderlab.org.  Could you give me more context for this issue?

I used this text:


Induced pluripotent stem (iPS) cells can be generated from somatic cells by introduction of Oct3/4, Sox2, Klf4 and c-Myc, in mouse1-4 and human5-8. Efficiency of this process, however, is low9. Pluripotency can be induced without c-Myc, but with even lower efficiency10,11. A p53 siRNA was recently shown to promote human iPS cell generation12, but specificity and mechanisms remain to be determined. Here we report that up to 10% of transduced mouse embryonic fibroblasts (MEF) lacking p53 became iPS cells, even without the Myc retrovirus. The p53 deletion also promoted induction of integration-free mouse iPS cells with plasmid transfection. Furthermore, in the p53-null background, iPS cells were generated from terminally differentiated T lymphocytes. Suppression of p53 also increased the efficiency of human iPS cell generation. DNA microarray analyses identified 34 p53-regulated genes that are common in mouse and human fibroblasts. Functional analyses of these genes demonstrate that the p53-p21 pathway serves as a safeguard not only in tumorigenicity, but also in iPS cell generation.

**Comment by jvwong** [comment] 2018-03-07 16:04
FYI, may refer to #179. There was a server-side error on the 'debug' text input page, but this was by design: Factoid was rejecting REACH results when entity grounding was deemed 'erroneous', in this case, some entity xref had an unsupported species. I think we switched this behaviour off.

**Comment by d2fong** [comment] 2018-03-07 22:20
So does it make sense to turn this behaviour back on and then log errors?

**Comment by maxkfranz** [comment] 2018-03-08 16:24
I don't think we should change the Reach postprocessing.  We should log errors from generating documents from Reach though.  I suppose it would be a rejected promise in `reach.js` `get()`.

**Comment by sacdallago** [comment] 2018-03-08 18:42
@d2fong RE https://github.com/PathwayCommons/factoid/issues/172#issuecomment-371186410 : I can't emulate this behaviour anymore either. I think the problem back then was due to the confusion of which endpoint (arizona vs local docker) was being used. I assume that now we are always using the docker instance.

Now in general: I agree with @maxkfranz . We shouldn't block execution, but log the errors, make the user aware that something went wrong (maybe not too much in detail), have a way of letting us know what exactly went wrong and then just let the user work with either a blank document or with the _healthy_ part of REACH's response

**Comment by maxkfranz** [comment] 2018-03-08 18:46
It's still an open question as to whether a real user would actually enter text into Factoid, but in any case the real value is just in capturing the errors and knowing which texts caused issues that we need to work around.

We don't have user-facing UI for entering text into Factoid, so talking about error message UI is premature.  If we decide to allow text input, then I think we can discuss it in another issue for text input UI design.

**Comment by d2fong** [comment] 2018-03-22 17:20
We log text and errors that REACH throws now so I think we can close this

**Closed** 2018-03-22 17:20 UTC
Labels: enhancement
